### ISSUE TITLE
Tweaked I-sheet-you-not

### ISSUE THREAD

**Issue by Cybesjie** [alfredapp/updated-third-party-python2-workflows#40]
### Workflow name

I Sheet You Not(tweaked)

### Workflow page

https://www.alfredforum.com/topic/9469-i-sheet-you-not-plug-excel-into-alfred/

### Extra details

Everything works fine except for creating new workflows. I get the following error when generate a new workflow:

ERROR: I Sheet You Not[Run Script] Building workflow "test wf" in /Users/xin/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-i-sheet-you-not.c377cb825e93476a927dd646a46b24c5 ...
env: python: No such file or directory

The directory does exists in Finder, but the error raises anyway.

Could someone help me fix this?

**Comment by vitorgalvao** [comment]
How exactly are you running the Workflow? I need details to know where to look for. Also, if you downloaded that one over 10 days ago [get it again](https://github.com/alfredapp/updated-third-party-python2-workflows/raw/main/Workflows/I%20Sheet%20You%20Not.alfredworkflow) because it has been updated since.

**Comment by Cybesjie** [comment]
I downloaded the latest version, and the problem solved. Thank you!
